### ISSUE TITLE
SDK_TRACE_Print

### ISSUE THREAD

**Issue by paulrozhkin** [lmtspbru/SDK_cLAB#2]
С функцией SDK_TRACE_Print работать не удобно. Хотелось бы видеть функционал, как в printf(...).
Ожидаемый результат:
```
SDK_TRACE_Print("Total found devices: %d\n", devices);
```
Фактический результат:
```
char string[100];
sprintf(string, "Total found devices: %d\n", devices);
SDK_TRACE_Print(string);
```

**Comment by vakluchev** [comment]
SDK_TRACE_Print("%s%d%s%X", "Decimal value: ", 255, " Hex value: ", 255);

**Comment by vakluchev** [comment]
@paulrozhkin, обновил функцию.
`SDK_TRACE_Print("%s%d%s%X", "Decimal value: ", 255, " Hex value: ", 255);`
Результат: 2509.853:	Decimal value: 255 Hex value: FF
