### ISSUE TITLE
UART interface and pins?

### ISSUE THREAD

**Issue by paulrozhkin** [lmtspbru/SDK_cLAB#3]
Можно ли узнать, какие интерфейсы UART перемкнуты между собой для работы на стендах и какие там пины в тестовой версии cLAB? Я очень не хочу искать это сам попытками заливания кода и просмотра схемотехники.

**Comment by vakluchev** [comment]
UART2 и UART3 соединены попарно TX в RX.
PD5     ------> USART2_TX
PD6     ------> USART2_RX
PD8     ------> USART3_TX
PD9     ------> USART3_RX
